---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: backend-db
spec:
  selector:
    matchLabels:
      app: backend-db
  template:
    metadata:
      labels:
        app: backend-db
    spec:
      containers:
        - name: database
          image: postgres:16.3-bullseye
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
          env:
            - name: POSTGRES_PASSWORD
              value: "backend"
            - name: POSTGRES_USER
              value: "backend"
            - name: POSTGRES_DB
              value: "backend"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: "backend-db-service"
spec:
  selector:
    app: backend-db
  ports:
    - port: 5432
      targetPort: 5432
---
