---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "backend"
  name: "backend-ollama"
spec:
  selector:
    matchLabels:
      app: "ollama"
  template:
    metadata:
      labels:
        app: "ollama"
    spec:
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: ollama-model-persistent-volume-claim
        - name: file-storage
          persistentVolumeClaim:
            claimName: ollama-file-persistent-volume-claim
      containers:
        - name: ollama
          image: ollama/ollama:latest
          volumeMounts:
            - name: model-storage
              mountPath: /root/.ollama
              subPath: ollama-model
            - name: file-storage
              mountPath: /model_files
              subPath: ollama-file
          entrypoint: ["/bin/sh", "/model_files/run_ollama.sh"]
          ports:
            - containerPort: 11434
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-persistent-volume-claim
  namespace: resource
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-file-persistent-volume-claim
  namespace: resource
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: "backend"
  name: "ollama-service"
spec:
  selector:
    app: "ollama"
  ports:
    - port: 11434
      targetPort: 11434

---
